---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kbot
  namespace: kbot-otel
spec:
  interval: 1m0s
  ref:
    tag: v2.1.3
  url: https://github.com/yevgen-grytsay/kbot
